배열 정의하기

In [2]:
import numpy as np

a= np.array([[2, 3], [5 ,2]])
a

array([[2, 3],
       [5, 2]])

배열 슬라이싱

In [4]:
d = np.array([[1,2,3,4,5],[2,4,5,6,7,],[5,7,8,9,9,]])
d

array([[1, 2, 3, 4, 5],
       [2, 4, 5, 6, 7],
       [5, 7, 8, 9, 9]])

In [5]:
d[1][2]

5

In [6]:
d[1,2]

5

In [7]:
d[1:,3:]    # 1행 다음, 3열 다음 수만 출력

array([[6, 7],
       [9, 9]])

배열 크기 알아내기

In [9]:
d = np.array([2,3,4,5,6])
d        

array([2, 3, 4, 5, 6])

In [10]:
d.shape     # 한 개의 리스트에 각 다섯 개의 원소를 가지고 있음

(5,)

In [13]:
e = np.array([[1,2,3,4],[3,4,5,6]])
e

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [15]:
e.shape      # 두 개의 리스트에 각 네 개의 원소를 가지고 있음

(2, 4)

배열의 원소 유형 확인 : dtype

In [17]:
d.dtype

dtype('int32')

배열 유형 바꾸기 : astype()

In [18]:
data = np.arange(1,5)
data.dtype

dtype('int32')

In [19]:
data.astype('float64')     # 원소를 모두 실수로 변경

array([1., 2., 3., 4.])

In [20]:
data.astype('int32')      # 다시 정수로 변경

array([1, 2, 3, 4])

넘파이 함수

1)  0로 이루어진 배열 만들기 : np.zeros()

In [21]:
np.zeros((2,10))           # 행이 2이고 열이 10이며 각 원소가 0

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

1)  1로 이루어진 배열 만들기 : np.ones()

In [22]:
np.ones((2,10))         # 행이 2이고 열이 10이며 각 원소가 1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

3) 연속형 정수 생성 : np.arange()
- 특정 범위에 있는 원소를 자동 생성

In [23]:
np.arange(2,10)    # 2이상 10 미만의 원소로 이루어진 1차원 배열 생성

array([2, 3, 4, 5, 6, 7, 8, 9])

4. 행과 열을 다루기 : np.transpose()

In [24]:
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
b = np.transpose(a)     #a 에 저장된 배열의 행과 열을 바꿔 b에 저장
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

5. 배열의 사칙연산

In [28]:
arr1 = np.array([[2,3,4],[6,7,8]])
arr2 = np.array([[12,23,14],[36,47,58]])

In [29]:
# 배열의 덧셈
arr1 + arr2      # arr1[0] 와 arr2[0] 계산

array([[14, 26, 18],
       [42, 54, 66]])

In [30]:
# 배열의 곱셈
arr1 * arr2      # 같은자리 원소끼리 곱함(행렬의 곱셈과 다름)

array([[ 24,  69,  56],
       [216, 329, 464]])

In [31]:
# 배열의 나눗셈
arr1 / arr2      # 같은자리 원소끼리 나눔

array([[0.16666667, 0.13043478, 0.28571429],
       [0.16666667, 0.14893617, 0.13793103]])

In [34]:
# 크기가 서로 다르 배열끼리 더하기

arr3 = np.array([100,200,300])
arr1 + arr3

array([[102, 203, 304],
       [106, 207, 308]])

In [35]:
arr4 = np.array([1,2,3,4,5,6,7,8,8,10])
arr1 + arr4     # 행과 열의 크기가 모두 다 다른 배열은 더할 수 없음

ValueError: operands could not be broadcast together with shapes (2,3) (10,) 

In [37]:
arr5 = np.array([[9],[3]])
arr1 + arr5

array([[11, 12, 13],
       [ 9, 10, 11]])

In [38]:
arr1

array([[2, 3, 4],
       [6, 7, 8]])

인덱싱과 슬라이싱 

In [39]:
arr4 = np.arange(10)
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
arr4[:5]

array([0, 1, 2, 3, 4])

In [41]:
arr4[-3:]

array([7, 8, 9])

In [42]:
arr1

array([[2, 3, 4],
       [6, 7, 8]])

In [43]:
arr1[:,2]  #모든 리스트의 세 번째 원소를 슬라이싱

array([4, 8])

설문지 데이터 전처리

In [44]:
import usecsv, os
import numpy as np
os.chdir(r'C:\Users\kke86\OneDrive\바탕 화면\data_python\data_python\Basic')
quest = np.array(usecsv.switch(usecsv.opencsv('quest.csv')))    # quest.csv 파일을 열어 숫자 원소를 실수형으로 바꾼 다음 배열 형태로 quest 객체에 저장

In [45]:
quest

array([[1., 2., 1., 2., 2.],
       [1., 3., 2., 3., 2.],
       [1., 4., 3., 3., 3.],
       [2., 5., 4., 4., 4.],
       [2., 5., 6., 2., 5.],
       [3., 6., 4., 2., 5.],
       [3., 5., 4., 1., 6.],
       [3., 5., 5., 1., 3.]])

In [47]:
quest > 5    # 5보다 크면 True 5보다 작으면 Fasle

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False,  True, False, False],
       [False,  True, False, False, False],
       [False, False, False, False,  True],
       [False, False, False, False, False]])

In [48]:
quest[quest > 5]

array([6., 6., 6.])

In [50]:
quest[quest > 5] = 5    # 5보다 큰 수를 모두 5로 변경
quest

array([[1., 2., 1., 2., 2.],
       [1., 3., 2., 3., 2.],
       [1., 4., 3., 3., 3.],
       [2., 5., 4., 4., 4.],
       [2., 5., 5., 2., 5.],
       [3., 5., 4., 2., 5.],
       [3., 5., 4., 1., 5.],
       [3., 5., 5., 1., 3.]])

In [51]:
usecsv.writecsv('resultcsv.csv', list(quest))

### 사업성 분석
경제적 타당성: 이 사업이 비용 대비 얼마나 많은 효용을 갖다 줄 수 있는지를 나타내는 개념

-경제적 타당성을 분석하는 핵심 지표
- 순현재가치(Net Present Value, NPV) : 할인된 현금 흐름의 값을 모두 더한 값
- 내부수익률(Internal Rate of Return,IRR) : 순현재가치를 0으로 만드는 할인률

[ 자본의 현재 가치 구하기 ]

In [52]:
import numpy as np
discount = .05   # 할인률 5%
cashflow = 100   # 현금 흐름은 100(억 원)

In [53]:
# 현재가치(pv)를 구하는 함수
def presentvalue(n):
    return (cashflow / ((1+discount) ** n))

In [54]:
# 1년이 지났을 때 자본의 현재 가치
print(presentvalue(1))

95.23809523809524


In [55]:
# 2년이 지났을 때 자본의 현재 가치
print(presentvalue(2))

90.70294784580499


In [56]:
# 20년 동안 발생할 현재 가치
for i in range(20):
    print(presentvalue(i))

100.0
95.23809523809524
90.70294784580499
86.3837598531476
82.27024747918819
78.35261664684589
74.62153966366274
71.06813301301213
67.6839362028687
64.46089162177971
61.39132535407592
58.46792890864373
55.68374181775592
53.03213506452945
50.506795299551854
48.101709809096995
45.811152199140004
43.62966876108571
41.5520654867483
39.57339570166504


[ 놀이공원 사업성 분석 ]

1) 세부 지표 값 구하기

In [57]:
loss = [-750, -250]    # 1,2년 차에 발생한 비용
profit = [100] * 18    # 3년 차부터 발생한 이익
profit

[100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100]

In [60]:
cf = loss + profit  # 20년 동안 현금흐름
cf

[-750,
 -250,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100]

In [61]:
len(cf)

20

In [62]:
cashflow = np.array(cf)

2. 순 현재 가치(NPV)와 내부 수익률(IRR) 구하기
- 순현재가치 : np.npv(할인률, 현금 흐름)
- 현금 흐름 : np.irr(현금 흐름)

In [ ]:
import numpy as np
npv = np.npv(0.045, cashflow)   # 순현재 가치 출력
npv

In [ ]:
irr = np.iff(cashflow)
irr                      # 내부수익률을 출력

In [ ]:
# 내부 수익률
irr   # 0.06434936937255586
    # 가정된 할인률은 4.5% 6.4%는 4.5%높기 때문에 수익성이 있다.

In [ ]:
# 순현재가치
npv  # 174.4011295118405